create table
  public.polls (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    question text not null,
    options text[] not null,
    created_by uuid null,
    constraint polls_pkey primary key (id),
    constraint polls_created_by_fkey foreign key (created_by) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.votes (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    poll_id bigint not null,
    "option" text not null,
    voted_by uuid not null,
    constraint votes_pkey primary key (id),
    constraint votes_poll_id_fkey foreign key (poll_id) references polls (id) on update cascade on delete cascade,
    constraint votes_voted_by_fkey foreign key (voted_by) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;
